services:
  app:
    build: ./app
    networks:
      - app-network

  proxy:
    build: ./proxy
    ports:
      - 80:8080
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge